### ISSUE TITLE
Wrote my own version, thanks for inspiration!

### ISSUE THREAD

**Issue by YellowOnion** [noodlebox/stream-announcer#2]
My system already has python & requests installed, so I figured it might be a bit cleaner this way.

```
#!/usr/bin/env python

import requests

message = "I am live on [Twitch](<https://twitch.tv/blah> ) & [YouTube](<https://gaming.youtube.com/channel/blah/live> )!"


payload = { "content": message,
        "avatar_url" : "https://cdn.discordapp.com/avatars/user_id/hash.png",
        "username": "blah"
        }

r = requests.post( "https://discordapp.com/api/webhooks/blah/blah", json = payload )

```

**Comment by noodlebox** [comment]
For sure, Python definitely makes handling json easier! If you wanted to replicate the "stop" message functionality too, you could use the `signal` library to set up the handler for `SIGTERM`.

(I know it's been a few years, but I just noticed the open issue :sweat_smile:)
